# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assets-service-account

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      serviceAccountName: assets-service-account
      containers:
        - name: assets-container
          image: arsenet10/revive-assets:01 # Replace with your actual container image
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "200m"
              memory: "64Mi"
            requests:
              cpu: "100m"
              memory: "32Mi"

---
# Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: assets
spec:
  type: ClusterIP
  selector:
    app: assets
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# Horizontal Pod Autoscaler (HPA)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: assets-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assets-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
