# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout-service-account

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
data:
  REDIS_URL: "redis://checkout-db:6379"
  ENDPOINTS_ORDERS: "http://orders:8080"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-deployment
spec:
  replicas: 
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      serviceAccountName: checkout-service-account
      containers:
        - name: checkout-container
          image: arsenet10/revive-checkout:01 # Replace with your actual container image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: checkout-config      # Refer to ConfigMap
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"

---
# Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# Horizontal Pod Autoscaler (HPA)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: checkout-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkout-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
