# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-service-account

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  DB_HOST: orders-db
  DB_NAME: orders

---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  DB_USER: "b3JkZXJzX3VzZXI="
  DB_PASSWORD: "b3JkZXJzX3Bhc3M="
  
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      serviceAccountName: orders-service-account
      containers:
        - name: orders-container
          image: arsenet10/revive-orders:01 # Replace with your actual container image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-config      # Refer to ConfigMap
            - secretRef:
                name: orders-secret         # Refer to Secret            
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "200m"
              memory: "128Mi"

---
# Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# Horizontal Pod Autoscaler (HPA)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: orders-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
